#ifndef SACI_PLATFORM_CONFIG_INTERNAL_RENDERER_CONFIG_DEFAULT_COMMONS_H
#define SACI_PLATFORM_CONFIG_INTERNAL_RENDERER_CONFIG_DEFAULT_COMMONS_H

#include "saci_util/types.h"

const SaciU64 PSACI_G_PSACI_CONFIG_RENDERER_DEFAULT_FIELDX = 0,
              PSACI_G_PSACI_CONFIG_RENDERER_DEFAULT_INSTANCE_FIELD_COUNT = 14;

#endif // SACI_PLATFORM_CONFIG_INTERNAL_RENDERER_CONFIG_DEFAULT_COMMONS_H
