#ifndef SACI_UTIL_INTERNAL_MAX_VALUES_H
#define SACI_UTIL_INTERNAL_MAX_VALUES_H

// 2^20
#define SACI_MAX_STRING_SIZE 1048576
// 2^7
#define SACI_MAX_CONFIG_FIELD_STRING_SIZE_SMALL 128
// 2̛̛^14
#define SACI_MAX_CONFIG_FIELD_STRING_SIZE 16384

#endif // SACI_UTIL_INTERNAL_MAX_VALUES_H
